import rawMetrics from "@/data/logo-metrics.json";

/**
 * Sizing for the sponsor logo walls.
 *
 * Logos were previously laid out at a fixed height (`h-14 w-auto`). Holding
 * height constant is the one choice guaranteed to make mixed logo shapes look
 * mismatched: at 56px tall a 6:1 wordmark covers roughly thirteen times the
 * area of a square badge, so the badge reads as "broken" even when its artwork
 * fills its canvas perfectly.
 *
 * Instead we hold *area* roughly constant, which is the established fix for
 * logo strips. Each logo gets a shape weight
 *
 *     w = aspect x coverage^DENSITY
 *
 * and a height of `base x sqrt(REFERENCE_WEIGHT / w)`. A logo of median shape
 * lands at exactly `base`; wider ones get shorter, squarer ones taller, and the
 * rendered area stays near `base^2` in every case.
 *
 * `coverage` (the share of the tight bounding box that is actually ink) damps
 * the result: SKF is a dense filled block and Michigan Scientific is hairline
 * type, and treating their bounding boxes as equally "heavy" over-weights SKF.
 * DENSITY = 0 is pure equal-bounding-box-area, 1 is pure equal-ink-area; 1 is
 * far too aggressive and balloons the thinnest marks, so we damp rather than
 * fully correct.
 *
 * Both inputs come from src/data/logo-metrics.json, regenerated by
 * `node scripts/build-logos.mjs --write` whenever logos are added or changed.
 */

type Metric = { aspect: number; coverage: number; rasterized?: boolean; opaqueBackground?: boolean };
const metrics = rawMetrics as Record<string, Metric>;

export type TierKey = "ultimate" | "platinum" | "gold" | "silver" | "bronze" | "marquee";

/**
 * `base` is the height a median-shaped logo gets, and rendered area scales with
 * base^2 -- so ordering these values is what keeps Ultimate visibly weightier
 * than Bronze. Tune the hierarchy here and nowhere else.
 */
const TIER_BASE: Record<TierKey, number> = {
  ultimate: 78,
  platinum: 64,
  gold: 56,
  silver: 47,
  bronze: 40,
  marquee: 48,
};

const DENSITY = 0.35;

/**
 * Median shape weight across all logos currently on the site (71 assets).
 * Fixed deliberately rather than recomputed: deriving it from the live set
 * would make every logo on the page resize slightly each time a sponsor is
 * added. Recompute it only if the mix of logo shapes changes wholesale.
 */
const REFERENCE_WEIGHT = 2.3332;

/** Clamps, as a multiple of the tier base. The ceiling is the one that matters:
 *  without it a near-square badge grows tall enough to crowd its row. */
const MIN_SCALE = 0.62;
const MAX_SCALE = 1.5;

export type LogoBox = { width: number; height: number };

export function logoBox(file: string, tier: TierKey, scale = 1): LogoBox {
  const base = TIER_BASE[tier] * scale;
  const m = metrics[file];

  // No metrics (a logo added without rerunning the build script): fall back to
  // the old fixed-height behaviour rather than guessing at a shape.
  if (!m) return { width: Math.round(base * 3), height: Math.round(base) };

  const weight = m.aspect * Math.pow(m.coverage, DENSITY);
  const raw = base * Math.sqrt(REFERENCE_WEIGHT / weight);
  const height = Math.min(base * MAX_SCALE, Math.max(base * MIN_SCALE, raw));

  return { width: Math.round(height * m.aspect), height: Math.round(height) };
}

/** Path to the trimmed asset. Four SVGs carry live <text> and were rasterised
 *  by the build script, so they resolve to PNG regardless of the `png` flag. */
export function logoSrc(file: string, png?: boolean): string {
  if (metrics[file]?.rasterized || png) return `/logo/sponsor/trimmed/${file}.png`;
  return `/logo/sponsor/trimmed/svg/${file}.svg`;
}
